//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string PatientName { get; set; }
        public string PatientEmail { get; set; }
        public int PatientPhone { get; set; }
        public string AppointmentStatus { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
